annotations

diff --git a/zz-annotations/annotations b/zz-annotations/annotations
--- a/zz-annotations/annotations
+++ b/zz-annotations/annotations
@@ -208,6 +208,9 @@ oc get istag
 --Describe the container image
 oc describe is hello-world
 
+-- Show the images on the openshift
+oc get is -n openshift
+
 
 ---------------------- Managing Application Builds -------------------
 https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/cicd/index#basic-build-operations
@@ -244,6 +247,207 @@ spec:
 oc set env bc/name BUILD_LOGLEVEL="4" ## 0 - 5
 
 
+-- Create a application from source
+oc new-app --name jhost \ 1 - Create a new app
+--build-env MAVEN_MIRROR_URL=http://${RHT_OCP4_NEXUS_SERVER}/repository/java \ -- set the env variable
+-i redhat-openjdk18-openshift:1.8 \  -- Specifies the image to be used for the build
+https://github.com/${RHT_OCP4_GITHUB_USER}/DO288-apps#manage-builds \
+--context-dir java-serverhost -- Specifies a subdirectory within the source repository (java-serverhost) as the build context
+
+oc new-app --name usuario-app \
+--build-env MAVEN_MIRROR_URL=https://repo1.maven.org/maven2 \
+-i ubi8-openjdk-17:1.11 \
+https://github.com/marciodevelopment/usuario-op#manage-builds
+
+
+oc new-app --name usuario-app-spring \
+--build-env MAVEN_MIRROR_URL=https://repo1.maven.org/maven2 \
+-i java-springboot-image:latest \
+https://github.com/marciodevelopment/usuario-op#manage-builds
+
+
+oc new-app --name usuario-app-spring \
+--build-env MAVEN_MIRROR_URL=https://repo1.maven.org/maven2 \
+-i java-springboot-image:latest \
+https://github.com/devfile-samples/devfile-sample-java-springboot-basic
+
+
+-- show the builds configuration
+oc get bc
+
+--List all builds available in the project:
+oc get builds
+
+-- Start a new build with the oc start-build command:
+oc start-build bc/jhost
+
+--------- Triggering Builds -------------
+https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/cicd/index#triggering-builds-build-hooks
+** To view the triggers associated with a build configuration
+oc describe bc/name
+
+** To add an image change trigger to a build configuration, use the oc set triggers command
+oc set triggers bc/name --from-image=project/image:tag
+
+** To remove an image change trigger from a build configuration
+ oc set triggers bc/name --from-image=project/image:tag --remove
+
+** Add a GitLab webhook to a build configuration:
+oc set triggers bc/name --from-gitlab
+
+** Remove
+oc set triggers bc/name --from-gitlab --remove
+
+** Create secret to acess de quay registry
+oc create secret generic quay-registry \
+--from-file .dockerconfigjson=${XDG_RUNTIME_DIR}/containers/auth.json \
+--type kubernetes.io/dockerconfigjson
+
+** Add the Quay.io registry secret to the builder service account.
+oc secrets link builder quay-registry
+
+
+
+** Update the php image stream to fetch the metadata for the new container image. The external registry uses the docker-distribution package and does not notify Red Hat OpenShift about image changes.
+oc import-image php --from quay.io/${RHT_OCP4_QUAY_USER}/php-73-ubi8 --confirm
+
+
+------ Implementing Post-commit Build Hooks-----
+https://access.redhat.com/documentation/en-us/openshift_container_platform/4.6/html-single/builds/triggering-builds-build-hooks
+A typical scenario to use a post-commit build hook is to execute some tests in your application. This way, before RHOCP pushes the image to the registry and starts a new deployment, tests can check if the application is working correctly. If the test fails, the build fails and does not continue with a deployment.
+There are a few other common use cases where it can be useful to leverage a post-commit build hook. For example:
+To integrate a build with an external application through an HTTP API.
+To validate a non-functional requirement such as application performance, security, usability, or compatibility.
+To send an email to the developer's team informing them of the new build
+
+** A command is executed using the exec system call. 
+Create a command post-commit build hook using the --command option as shown 
+in the following command:
+oc set build-hook bc/name --post-commit \
+--command -- bundle exec rake test --verbose
+
+** Runs a build hook with the /bin/sh -ic command. This is more convenient 
+since it has all the features provided by a shell, such as argument expansion, 
+redirection, and so on. It only works if the base image has the sh shell. 
+Create a shell script post-commit build hook using the --script as shown in 
+the following command:
+oc set build-hook bc/name --post-commit \
+--script="curl http://api.com/user/${USER}"
+
+
+
+-- Deploy a new application using version ~
+oc new-app --name hook --context-dir post-commit \
+php:7.3~http://github.com/${RHT_OCP4_GITHUB_USER}/DO288-apps
+
+------------------------------------------------------
+Describing the Source-to-Image Architecture
+------------------------------------------------------
+* assemble	 
+The assemble script builds the application from source and places it into appropriate directories inside the image.
+
+* run	       
+The run script executes your application. It is recommended to use the exec command when running any container processes in your run script. This ensures 
+signal propagation and graceful shutdown of any process launched by the run script.
+
+* save-artifacts	
+The save-artifacts script gathers all dependencies required for the application and saves them to a tar file to speed up subsequent builds. For example, for Ruby, gems installed by Bundler, or for Java, .m2 contents. This means that the build does not have to redownload these contents, improving build time. These dependencies are gathered into a tar file and streamed to the standard output.
+
+* usage
+The usage script provides a description of how to properly use your image.
+
+* test/run	
+The test/run script allows you to create a simple process to verify if the image is working correctly.
+
+
+
+
+--------- Customizing an Existing S2I Base Image ------
+-- Use the podman pull command to pull the container image from a conatiner registry to the local system. 
+* podman pull myregistry.example.com/rhscl/php-73-rhel7
+
+-- Use the podman inspect command to get the value of the io.openshift.s2i.scripts-url label, in order to determine the default location of the S2I scripts in the image.
+* podman inspect --format='{{ index .Config.Labels "io.openshift.s2i.scripts-url"}}' rhscl/php-73-rhel7
+
+-- Create a wrapper for the assemble script in the .s2i/bin folder
+#!/bin/bash
+echo "Making pre-invocation changes..."
+/usr/libexec/s2i/assemble
+rc=$?
+if [ $rc -eq 0 ]; then
+    echo "Making post-invocation changes..."
+else
+    echo "Error: assemble failed!"
+fi
+exit $rc
+
+-- Similarly, create a wrapper for the run script in the .s2i/bin folder:
+-- wrapping the run script, you must use exec to invoke it.
+#!/bin/bash
+echo "Before calling run..."
+exec /usr/libexec/s2i/run
+
+---- Incremental Builds in S2I ----
+https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/images/index#creating-images
+https://cloud.redhat.com/blog/override-s2i-builder-scripts
+
+The S2I build process provides a mechanism to reduce build time by invoking the save-artifacts script after invoking the assemble script
+Dependent artifacts (libraries and components required for the application) are saved for future builds
+The save-artifacts script output should only include the tar stream output, and nothing else
+You should redirect output of other commands in the script to /dev/null.
+
+The save-artifacts script that caches Maven JAR files can be defined as follows:
+#!/bin/sh -e
+# Stream the .m2 folder tar archive to stdout
+if [ -d ${HOME}/.m2 ]; then
+    pushd ${HOME} > /dev/null
+    tar cf - .m2
+    popd > /dev/null
+fi
+
+The corresponding code to restore the artifacts before building is in the assemble script:
+# Restore the .m2 folder
+...output omitted...
+if [ -d /tmp/artifacts/.m2 ]; then
+  echo "---> Restoring maven artifacts..."
+  mv /tmp/artifacts/.m2 ${HOME}/
+fi
+
+
+
+- Run the image
+podman run --name test -it quay.io/centos7/httpd-24-centos7 bash
+- Inspect the S2I scripts
+bash-4.2$ cat /usr/libexec/s2i/assemble
+bash-4.2$ cat /usr/libexec/s2i/run
+bash-4.2$ cat /usr/libexec/s2i/usage
+
+
+--- Deploy the application to a RHOCP cluster. Verify that the custom S2I scripts are executed.
+
+marciodevelopment
+marciodevelopment
+marciodevelopement
+
+oc new-app \
+--name bonjour \
+httpd:latest~https://github.com/marciodevelopment/DO288-apps#manage-builds \
+--context-dir s2i-scripts
+
+
+
+------------ Creating an S2I Base Image S05 ----------
+https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html-single/images/index
+https://cloud.redhat.com/blog/create-s2i-builder-image
+https://github.com/openshift/source-to-image
+https://github.com/openshift/source-to-image/blob/master/docs/cli.md
+
+S2I build process  -> source code + s2i builder image -> application container
+--- Installing the S2I Tool
+To teste the image
+
+
+
 
 
 
@@ -272,7 +476,8 @@ Log in as user:
 
   $ eval $(crc oc-env)
   $ oc login -u developer https://api.crc.testing:6443
-  oc login -u kubeadmin https://api.crc.testing:6443
+  
+  
 
 
 
